apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-fs
spec:
  capacity:
    storage: 1T
  accessModes:
  - ReadWriteMany
  nfs:
    path: /{{ .Values.config.fsPath }}
    server: {{ .Values.config.fsAddr }}
