replicasCount: 1
maxUnavailableCount: 0

image:
  repository: registry.videocoin.net/cloud/uploader
  tag: latest
  pullPolicy: Always
  pullSecrets:
  - name: regcred

config: {}

serviceAccount:
  name: default

service:
  type: ClusterIP
  externalHttpPort: 8090
  http: 8090

autoscaler:
  minCount: 1
  maxCount: 10
  targets:
    targetCPUUtilizationPercentage: 70

resources: {}

config:
  streamsRpcAddr: streams.console.svc.cluster.local:5102
  fsPath: /studio
  fsAddr: 10.129.14.250

annotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/role: "console-uploader"
  vault.hashicorp.com/agent-inject-secret-common: "videocoin/v1/networks/everest-dev/console/common"
  vault.hashicorp.com/agent-inject-secret-config: "videocoin/v1/networks/everest-dev/console/uploader"
  vault.hashicorp.com/agent-inject-template-common: |
    {{ with secret "videocoin/v1/networks/everest-dev/console/common" }}{{ range $k, $v := .Data }}
    export {{ $k }}="{{ $v }}"
    {{ end }}{{ end }}
  vault.hashicorp.com/agent-inject-template-config: |
    {{ with secret "videocoin/v1/networks/everest-dev/console/uploader" }}{{ range $k, $v := .Data }}
    export {{ $k }}="{{ $v }}"
    {{ end }}{{ end }}

