replicasCount: 3
maxUnavailableCount: 0

image:
  repository: gcr.io/videocoin-network/uploader
  tag: latest
  pullPolicy: Always

config: {}

service:
  type: ClusterIP
  externalHttpPort: 8090
  internalHttpPort: 8090

autoscaler:
  minCount: 1
  maxCount: 10
  targets:
    targetCPUUtilizationPercentage: 70

secrets:
  secret: ""
  sentryDsn: ""

resources: {}
