replicasCount: 1
maxUnavailableCount: 0

image:
  repository: registry.videocoin.net/cloud/uploader
  tag: latest
  pullPolicy: Always

config: {}

serviceAccount:
  name: default

service:
  type: ClusterIP
  externalHttpPort: 8090
  http: 8090

autoscaler:
  minCount: 1
  maxCount: 10
  targets:
    targetCPUUtilizationPercentage: 70

secrets:
  sentryDsn: ""
  redisUri: "cmVkaXM6Ly86cmVkaXNAcmVkaXMtbWFzdGVyOjYzNzkvMg=="
  authTokenSecret: "N012TnNxRVhxaXpuQmtDaQ=="
  gdriveKey: "QUl6YVN5RGhVZXNnN3FLeDZNbGgwY3dOR2I2cHZoZHZzaElocGU4"

resources: {}

config:
  streamsRpcAddr: streams.console.svc.cluster.local:5102
